### ISSUE TITLE
BUG pages only trigger items from first page

### ISSUE THREAD

**Issue by Armhole1225** [StreamController/StreamController#231]
**Describe the bug**
All items on page 1 work fine. When I switch to page 2 and select an action, it triggers the item on page 1 not on page 2

**To Reproduce**
1. Create an action on page 1
2. Create an action on page 2 the same stream deck button have a secondary action to switch back to main page
3. Switch to page 2 and select the action
5. You'll notice it runs the action from page 1

**Additional context**
this happened after running updates through pacman. I'm not exactly sure what update caused it.  I'll go through my updates but I had several updates.

Seems to work fine if you don't have it auto switch back to the main page after running  the action.

**Comment by v4u6h4n** [comment]
Think I might have the same issue, but its presenting a little differently, perhaps cause I have multiple decks. It only effecting my second deck, and its a bit unpredictable which button action is being triggered, but it is not the right one for button that I actually press.

**Comment by Core447** [comment]
@Armhole1225 Can you please export all required pages (via the hamburger menu of the page manager) and share them?

I tried the following setup and the action on "page1" doesn't get triggered when I press the action on "page2":
![image](https://github.com/user-attachments/assets/9ec28a21-f86c-49c7-b847-a417614c7f4f)
![image](https://github.com/user-attachments/assets/c89feba5-5246-4ded-87cc-386145f0bd7a)

**Comment by v4u6h4n** [comment]
Here's my export, and heres what I'm seeing in my console. Some of my streamdecks work, others do not, it seems to have started after a recent system update.

[StreamController_2024-09-19_10-27.json](https://github.com/user-attachments/files/17051749/StreamController_2024-09-19_10-27.json)


```
2024-09-19 10:26:26.076 | INFO     | src.backend.DeckManagement.DeckController:load_page:699 - Loaded page passive_unrestricted_unmuted on deck BL25K1B02763
2024-09-19 10:26:26.100 | ERROR    | src.backend.PageManagement.PageManagerBackend:get_page_json:371 - Invalid json in /home/v4u6h4n/.var/app/com.core447.StreamController/data/pages/passive_unrestricted_unmuted.json, falling back to backup
2024-09-19 10:26:26.101 | ERROR    | threading:run:1012 - An error has been caught in function 'run', process 'MainProcess' (27230), thread 'own_actions_event_callback' (124384222119616):
Traceback (most recent call last):

  File "/usr/lib/python3.12/threading.py", line 1032, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x712116d3ac00>
    └ <Thread(own_actions_event_callback, started 124384222119616)>
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x712116d3a8e0>
    └ <Thread(own_actions_event_callback, started 124384222119616)>
> File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(own_actions_event_callback, started 124384222119616)>
    │    │        │    └ (<Events.DOWN: 'Key Down'>, None, True)
    │    │        └ <Thread(own_actions_event_callback, started 124384222119616)>
    │    └ <bound method ControllerInputState.own_actions_event_callback of <src.backend.DeckManagement.DeckController.ControllerKeyStat...
    └ <Thread(own_actions_event_callback, started 124384222119616)>

  File "/home/v4u6h4n/StreamController/src/backend/DeckManagement/DeckController.py", line 1497, in own_actions_event_callback
    action.event_callback(parsed_event, data)
    │      │              │             └ None
    │      │              └ <Events.DOWN: 'Key Down'>
    │      └ <function ActionBase.event_callback at 0x7120e4b43600>
    └ <plugins.com_core447_DeckPlugin.main.ChangePage object at 0x7120bf59bf80>

  File "/home/v4u6h4n/StreamController/src/backend/PluginManager/ActionBase.py", line 102, in event_callback
    self.on_key_down()
    │    └ <function ChangePage.on_key_down at 0x7120d799b240>
    └ <plugins.com_core447_DeckPlugin.main.ChangePage object at 0x7120bf59bf80>

  File "/home/v4u6h4n/.var/app/com.core447.StreamController/data/plugins/com_core447_DeckPlugin/main.py", line 186, in on_key_down
    page = gl.page_manager.get_page(page_path, deck_controller=controller)
           │  │            │        │                          └ <src.backend.DeckManagement.DeckController.DeckController object at 0x7120c1ff5e50>
           │  │            │        └ '/home/v4u6h4n/.var/app/com.core447.StreamController/data/pages/passive_unrestricted_unmuted.json'
           │  │            └ <function PageManagerBackend.get_page at 0x7120da303b00>
           │  └ <src.backend.PageManagement.PageManagerBackend.PageManagerBackend object at 0x7120e21c1d30>
           └ <module 'globals' from '/home/v4u6h4n/StreamController/globals.py'>

  File "/home/v4u6h4n/StreamController/src/backend/PageManagement/PageManagerBackend.py", line 115, in get_page
    new_page = self.create_page(path, deck_controller)
               │    │           │     └ <src.backend.DeckManagement.DeckController.DeckController object at 0x7120c1ff5e50>
               │    │           └ '/home/v4u6h4n/.var/app/com.core447.StreamController/data/pages/passive_unrestricted_unmuted.json'
               │    └ <function PageManagerBackend.create_page at 0x7120da303a60>
               └ <src.backend.PageManagement.PageManagerBackend.PageManagerBackend object at 0x7120e21c1d30>

  File "/home/v4u6h4n/StreamController/src/backend/PageManagement/PageManagerBackend.py", line 98, in create_page
    page = Page(json_path=path, deck_controller=deck_controller)
           │              │                     └ <src.backend.DeckManagement.DeckController.DeckController object at 0x7120c1ff5e50>
           │              └ '/home/v4u6h4n/.var/app/com.core447.StreamController/data/pages/passive_unrestricted_unmuted.json'
           └ <class 'src.backend.PageManagement.Page.Page'>

  File "/home/v4u6h4n/StreamController/src/backend/PageManagement/Page.py", line 57, in __init__
    self.load(load_from_file=True)
    │    └ <function Page.load at 0x7120e4b4cf40>
    └ <src.backend.PageManagement.Page.Page object at 0x7120bf59ba70>

  File "/home/v4u6h4n/StreamController/src/backend/PageManagement/Page.py", line 73, in load
    self.load_action_objects()
    │    └ <function Page.load_action_objects at 0x7120e4b4d260>
    └ <src.backend.PageManagement.Page.Page object at 0x7120bf59ba70>

  File "/home/v4u6h4n/StreamController/src/backend/PageManagement/Page.py", line 125, in load_action_objects
    for key in self.dict.get(input_type, {}):
               │    │        └ 'keys'
               │    └ None
               └ <src.backend.PageManagement.Page.Page object at 0x7120bf59ba70>

AttributeError: 'NoneType' object has no attribute 'get'
2024-09-19 10:26:26.109 | INFO     | src.backend.DeckManagement.DeckController:load_all_inputs:608 - Loading all inputs took 0.03388786315917969 seconds
2024-09-19 10:26:26.114 | DEBUG    | src.backend.DeckManagement.DeckController:update_all_inputs:432 - Updating all inputs took 0.0047681331634521484 seconds
```

**Comment by Core447** [comment]
> I tried the following setup and the action on "page1" doesn't get triggered when I press the action on "page2":

Update: I'm now getting the same problem, as you @Armhole1225. It's probably related to the latest changes I made to the OS plugin. I hope that I can fix this soon.
@Armhole1225 Do you only have this for "run command" actions or for other ones as well?

@v4u6h4n The exception you posed seem to be directly related to the "change page" action, whereas the original issue is that the events get passed to the new page after a switch.

**Comment by Core447** [comment]
Should be fixed with https://github.com/StreamController/OSPlugin/commit/3ebb7b00fd89c0974a27c2fa294feab94a7bf89e. Can you please update the plugin in the store, restart the app and check if the issue is gone?

**Comment by v4u6h4n** [comment]
@Core447 thankyou :3 it looks like it's fixed now. Sweet relief. I had fallen back to hyprland submaps!

Just in case the clarification is helpful on your end troubleshooting what was actually fixed, I didn't seem to have had any issues with the change page actions, it was only the OS actions.

EDIT: Is there a way to rollback plugin updates as temporary fix if I run into another plugin issue in the future?

**Comment by Core447** [comment]
> thankyou :3 it looks like it's fixed now. Sweet relief.

Great!

> Just in case the clarification is helpful on your end troubleshooting what was actually fixed, I didn't seem to have had any issues with the change page actions, it was only the OS actions.

Ok, yeah the "Run command" action was behaving a bit weird.

> EDIT: Is there a way to rollback plugin updates as temporary fix if I run into another plugin issue in the future?

Yes, but not an easy (gui) one. You would have to do the following things:
- Disable auto updates in the settings
- delete the content of the plugin folder in `~/.var/app/com.core447.StreamController/data/plugins`
- Clone (or download) the plugin repo into the now empty folder
- Use `git checkout <commit_hash>` to specify a commit
- Run the `__install__.py` file of the plugin if present using `python3 __install__.py`
- optional: Create a file called `VERSION` (no extension) in the plugin dir that contains the complete hash of the commit you selected

**Comment by Armhole1225** [comment]
I'm sorry I didn't get back to you @Core447 . The update worked for me, thank you so much.

**Comment by Core447** [comment]
> thank you so much.

Not for this, I have to apologize because I pushed this to the store without proper testing and it took quite a while to fix it.

**Comment by v4u6h4n** [comment]
I'm still getting some of the same issue as before, or perhaps a different issue, but with similar symptoms. My export is the same as above, I'm getting this when I press some buttons that should be executing a script via the OS plugin, but not sure if it shows anything noteworthy...

```
2024-09-24 08:01:58.435 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:58.436 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:58.436 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:58.436 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:58.436 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:58.436 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:58.450 | DEBUG    | src.backend.PageManagement.Page:load:77 - Loaded page passive_unrestricted_unmuted in 0.02 seconds
2024-09-24 08:01:58.451 | INFO     | src.backend.DeckManagement.DeckController:load_page:670 - Loading page passive_unrestricted_unmuted on deck BL25K1B02780
2024-09-24 08:01:58.521 | INFO     | src.backend.DeckManagement.DeckController:load_page:699 - Loaded page passive_unrestricted_unmuted on deck BL25K1B02780
2024-09-24 08:01:58.575 | INFO     | src.backend.DeckManagement.DeckController:load_background:522 - Loading background in thread: 127694108886720
2024-09-24 08:01:58.576 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:58.577 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:58.577 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:58.577 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:58.627 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:58.627 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:58.652 | ERROR    | src.backend.PageManagement.Page:make_backup:103 - Invalid json in /home/v4u6h4n/.var/app/com.core447.StreamController/data/pages/passive_unrestricted_unmuted.json: Expecting value: line 1 column 1 (char 0)
2024-09-24 08:01:58.660 | INFO     | src.backend.DeckManagement.DeckController:load_all_inputs:608 - Loading all inputs took 0.032569169998168945 seconds
2024-09-24 08:01:58.669 | DEBUG    | src.backend.DeckManagement.DeckController:update_all_inputs:432 - Updating all inputs took 0.007197380065917969 seconds
2024-09-24 08:01:58.670 | DEBUG    | src.backend.PageManagement.Page:load:77 - Loaded page passive_unrestricted_unmuted in 0.09 seconds
2024-09-24 08:01:58.671 | INFO     | src.backend.DeckManagement.DeckController:load_page:670 - Loading page passive_unrestricted_unmuted on deck BL25K1B02779
2024-09-24 08:01:58.758 | INFO     | src.backend.DeckManagement.DeckController:load_page:699 - Loaded page passive_unrestricted_unmuted on deck BL25K1B02779
2024-09-24 08:01:58.809 | INFO     | src.backend.DeckManagement.DeckController:load_background:522 - Loading background in thread: 127694398293696
2024-09-24 08:01:58.837 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:58.838 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:58.838 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:58.838 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:58.838 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:58.839 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:58.860 | INFO     | src.windows.mainWindow.elements.PageSelector:on_change_page:127 - Load page: <src.backend.PageManagement.Page.Page object at 0x7423a5cfc9d0>
2024-09-24 08:01:58.862 | INFO     | src.backend.DeckManagement.DeckController:load_page:670 - Loading page passive_unrestricted_unmuted on deck BL25K1B02779
2024-09-24 08:01:58.865 | ERROR    | src.backend.PageManagement.Page:make_backup:103 - Invalid json in /home/v4u6h4n/.var/app/com.core447.StreamController/data/pages/passive_unrestricted_unmuted.json: Expecting value: line 1 column 1 (char 0)
2024-09-24 08:01:58.873 | INFO     | src.backend.DeckManagement.DeckController:load_all_inputs:608 - Loading all inputs took 0.03518080711364746 seconds
2024-09-24 08:01:58.876 | DEBUG    | src.backend.PageManagement.Page:load:77 - Loaded page passive_unrestricted_unmuted in 0.04 seconds
2024-09-24 08:01:58.878 | DEBUG    | src.backend.DeckManagement.DeckController:update_all_inputs:432 - Updating all inputs took 0.004453182220458984 seconds
2024-09-24 08:01:58.880 | INFO     | src.backend.DeckManagement.DeckController:load_page:670 - Loading page passive_unrestricted_unmuted on deck BL25K1B02763
2024-09-24 08:01:58.964 | INFO     | src.backend.DeckManagement.DeckController:load_page:699 - Loaded page passive_unrestricted_unmuted on deck BL25K1B02779
2024-09-24 08:01:58.995 | INFO     | src.backend.DeckManagement.DeckController:load_background:522 - Loading background in thread: 127693939017408
2024-09-24 08:01:58.995 | INFO     | src.backend.DeckManagement.DeckController:load_background:522 - Loading background in thread: 127694398293696
2024-09-24 08:01:59.034 | INFO     | src.backend.DeckManagement.DeckController:load_page:699 - Loaded page passive_unrestricted_unmuted on deck BL25K1B02763
2024-09-24 08:01:59.060 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:59.061 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:59.061 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:59.062 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:59.062 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:59.062 | INFO     | src.backend.PluginManager.ActionBase:__init__:77 - Loaded action Change Page with id com_core447_DeckPlugin::ChangePage
2024-09-24 08:01:59.085 | ERROR    | src.backend.PageManagement.Page:make_backup:103 - Invalid json in /home/v4u6h4n/.var/app/com.core447.StreamController/data/pages/passive_unrestricted_unmuted.json: Expecting value: line 1 column 1 (char 0)
2024-09-24 08:01:59.090 | INFO     | src.backend.DeckManagement.DeckController:load_all_inputs:608 - Loading all inputs took 0.07619047164916992 seconds
2024-09-24 08:01:59.100 | INFO     | src.backend.DeckManagement.DeckController:load_all_inputs:608 - Loading all inputs took 0.06575655937194824 seconds
2024-09-24 08:01:59.101 | DEBUG    | src.backend.DeckManagement.DeckController:update_all_inputs:432 - Updating all inputs took 0.01052999496459961 seconds
2024-09-24 08:01:59.107 | DEBUG    | src.backend.DeckManagement.DeckController:update_all_inputs:432 - Updating all inputs took 0.0060389041900634766 seconds
2024-09-24 08:01:59.113 | DEBUG    | src.backend.PageManagement.Page:load:77 - Loaded page passive_unrestricted_unmuted in 0.05 seconds
2024-09-24 08:01:59.117 | INFO     | src.backend.DeckManagement.DeckController:load_page:670 - Loading page passive_unrestricted_unmuted on deck BL19K1B01105
2024-09-24 08:01:59.203 | INFO     | src.backend.DeckManagement.DeckController:load_background:522 - Loading background in thread: 127693918045888
2024-09-24 08:01:59.246 | INFO     | src.backend.DeckManagement.DeckController:load_page:699 - Loaded page passive_unrestricted_unmuted on deck BL19K1B01105
2024-09-24 08:01:59.293 | INFO     | src.backend.DeckManagement.DeckController:load_all_inputs:608 - Loading all inputs took 0.021100282669067383 seconds
2024-09-24 08:01:59.295 | DEBUG    | src.backend.DeckManagement.DeckController:update_all_inputs:432 - Updating all inputs took 0.0017383098602294922 seconds
```

**Comment by Core447** [comment]
Can you check if the "Event Assigner" is set to the default for the problematic buttons?

**Comment by v4u6h4n** [comment]
Yeah they are all set to the default settings. The issue is inconsistent I've noticed; it only happens some of the time, like sometimes the same button will execute the script, other times, it will not...

**Comment by v4u6h4n** [comment]
I don't know what the problem was, but it seems to have fixed itself after a reboot *shrugs*
