### ISSUE TITLE
BUG: Incorrect rotation key mapping

### ISSUE THREAD

**Issue by gensyn** [StreamController/StreamController#378]
**Describe the bug**
When a Stream Deck is rotated in the settings, the keys in the map don't correspond to the keys on the Stream Deck. In my case I rotate my Stream Deck Mini 270° and add a Change Page action to the keys top left and bottom left. When I press the top left key on my deck, the Change Page action of the bottom left key is executed. The orientations of the icons on the keys are correct.

**To Reproduce**
1. Rotate deck by 270°.
2. Assign actions to top and bottom left keys.
3. Press top left key.

**Expected behavior**
The action of the correct key is executed.

PS: I just realized that the action being executed belongs to the original 0x0 key, not the rotated key. It seems like the view is rotated, but not the underlying keys.

**Comment by Core447** [comment]
Should be fixed by 0b9e02f24558edb6adc2397ceafce18174b62cbd. After changing the rotation in the ui, you'll probably have to restart (still working on a fix for that)

**Comment by gensyn** [comment]
Sorry, I thought I already gave feedback that executing an action on a rotated deck is still not working for me.

**Comment by violet4** [comment]
```
Exception in thread Thread-4 (_read_with_resume_from_suspend):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/app/lib/python3.12/site-packages/StreamDeck/Devices/StreamDeck.py", line 221, in _read_with_resume_from_suspend
    self.key_callback(self, k, new)
  File "/app/bin/StreamController/src/backend/DeckManagement/BetterDeck.py", line 217, in remapper_callback
    callback(deck, logical_key, state)
  File "/app/bin/StreamController/src/backend/DeckManagement/DeckController.py", line 453, in key_event_callback
    coords = ControllerKey.Index_To_Coords(deck, key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/StreamController/src/backend/DeckManagement/DeckController.py", line 1865, in Index_To_Coords
    y = index // cols
        ~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'
```

i would love to debug, but having some difficulty getting the project running from the command line.

i started from a fresh page. rotated 270 degrees. X means filled and O means not-filled. i tried to fill the entire stream deck with the same button and this is what i got:

```
XXXX
OOOO
XXXX
OOOO
XXXX
OOOO
XXXX
OOOO
```
(stream deck xl)

after restart, i'm able to place the same button in every position. then:

attempt to push the buttons - they correspond to the wrong index, i see the button press on a different button. keep pressing buttons, and there's clearly a failure condition that causes an internal crash. this is probably the traceback above. i can still see the buttons, but now no presses are registered. page can be switched but apparently button presses won't be recognized until the app is restarted.

**Comment by Core447** [comment]
I think all rotation problems are finally fixed with a066b2c7af676264f61c4454856d30cc2fa551c5
